### PR TITLE
Propel2 orm

### PR DESCRIPTION
**Pull request by motin**
Fixes https://github.com/kenjis/php-orm-benchmark/issues/2

Note: This pull request is based on the commits included in https://github.com/kenjis/php-orm-benchmark/pull/6 which either first should be merged, or this PR should be properly re-based upon the latest master before being merged.

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you. 

I ran the benchmark but I got the error:

> Compile Error - Controller_Orm_Propel2::setup(): Failed opening required '/mnt/project/php-orm-benchmark/fuel/app/../generated-conf/config.php' (include_path='.:/usr/share/pear:/usr/share/php') in /mnt/project/php-orm-benchmark/fuel/app/classes/controller/orm/propel2.php on line 10

**Comment by motin** [comment]
Try again now after 27792f3 :)

**Comment by kenjis** [comment]
The code has a bug. It seems the `order_by` condition https://github.com/kenjis/php-orm-benchmark/blob/master/fuel/app/classes/model/fuel/orm/post.php#L14 is missing.

**Comment by motin** [comment]
@kenjis Thanks I totally missed that part. Now fixed, and also the propel2 classes are put in a more appropriate folder.

**Comment by motin** [comment]
Let me know when you can merge https://github.com/kenjis/php-orm-benchmark/pull/6 so that I can rebase this PR properly upon the new master.

**Comment by kenjis** [comment]
Not fixed yet. Please fix the bug.

The result must be like this:

```
記事のテスト
2つ目のコメントです。      <-- here
0.075886011123657 secs
389.7265625 KB 
```

And please update your benchmarks.

You don't have to rebase. I have already merged in my local repository. So please just push the commit to fix it.

**Comment by motin** [comment]
@kenjis Done

**Comment by kenjis** [comment]
I merged, but does not work. So I fixed:
- https://github.com/kenjis/php-orm-benchmark/commit/3d5f431a0f1c87b9ecf0cbdac08dc1b2ad2854ac
- https://github.com/kenjis/php-orm-benchmark/commit/84bb2a946f323bd9ec3155f2e5924176644fe9ad

Thank you.

**Pull request closed without merging**
